name: diyar
description: "A new Flutter project."

publish_to: "none"

# version: 3.3.1+45 # This is andriod the version of the app.
version: 3.3.2+46 # This is  ios the version of the app.

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.13
  flutter_launcher_icons: ^0.13.1
  flutter_bloc: ^8.1.6
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  bloc: ^8.1.3
  meta: ^1.11.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.8
  auto_route: ^7.9.0
  dio: ^5.4.1
  jwt_decoder: ^2.0.1
  internet_connection_checker_plus: ^2.2.0
  dartz: ^0.10.1
  get_it: ^7.6.7
  url_launcher: ^6.3.0
  mask_text_input_formatter: ^2.9.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.1
  yandex_mapkit: ^4.0.2
  easy_stepper: ^0.8.3
  cloud_firestore: ^4.15.9
  easy_debounce: ^2.0.3
  fluttertoast: ^8.2.6
  web_socket_channel: ^2.4.5
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.8
  connectivity_plus: ^5.0.2
  keyboard_dismisser: ^3.0.0
  flutter_datetime_picker_plus: ^2.2.0
  package_info_plus: ^8.0.0
  carousel_slider: ^5.0.0
  pinput: ^5.0.0
  xml: ^6.5.0
  firebase_remote_config: ^4.4.7
  firebase_crashlytics: ^3.5.7
  firebase_analytics: ^10.10.7
  flutter_inappwebview: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.25.2
  mocktail: ^1.0.3

  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.11
  change_app_package_name: ^1.2.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#ffa462"
  image: "assets/images/app_icon.png"
  android: true
  ios: true

  android_12:
    image: assets/images/app_icon.png
    color: "#ffa462"
