name: diyar
description: "A new Flutter project."

publish_to: "none"

version: 3.4.6+72 

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: 3.27.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.13
  flutter_launcher_icons: ^0.14.2
  flutter_bloc: ^9.0.0
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  bloc: ^9.0.0
  meta: ^1.11.0
  firebase_core: ^4.3.0
  auto_route: ^9.2.2
  dio: ^5.4.1
  jwt_decoder: ^2.0.1
  internet_connection_checker_plus: ^2.2.0
  dartz: ^0.10.1
  get_it: ^9.2.0
  url_launcher: ^6.3.0
  mask_text_input_formatter: ^2.9.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  yandex_mapkit: ^4.2.1
  easy_debounce: ^2.0.3
  fluttertoast: ^9.0.0
  web_socket_channel: ^3.0.3
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.8
  connectivity_plus: ^7.0.0
  keyboard_dismisser: ^3.0.0
  flutter_datetime_picker_plus: ^2.2.0
  package_info_plus: ^8.0.0
  carousel_slider: ^5.0.0
  pinput: ^6.0.1
  xml: ^6.5.0
  firebase_remote_config: ^6.1.3
  flutter_image_compress: ^2.3.0
  logging: ^1.3.0
  flutter_cache_manager: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  photo_view: ^0.15.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  local_auth: ^2.3.0
  signalr_netcore: ^1.4.3
  collection: ^1.19.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  share_plus: ^12.0.1
  injectable: ^2.6.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  rest_client:
    path: ../package/rest_client
  storage:
    path: ../package/storage
  intl: ^0.20.2
  qr_flutter: ^4.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # СТАБИЛЬНЫЕ ВЕРСИИ
  build_runner: ^2.4.15
  freezed: ^2.5.7             # Ушли с багованной 3.0.0-dev
  json_serializable: ^6.9.0
  auto_route_generator: ^9.0.0
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#ffa462"
  image: "assets/images/app_icon.png"
  android: true
  ios: true

  android_12:
    image: assets/images/app_icon.png
    color: "#ffa462"
